Adding my first contribution
Yarob50/First-Contribution-ARABIC pull request #4
Opened 2023-05-07 17:25 UTC by dr-almukhtar

Please may i ask to accept my first contribution

2023-05-07 18:57 UTC, Yarob50 requested changes

2023-05-07 18:57 UTC, Yarob50 commented on readme.md
> +                    <!-- TWITTER -->
please modify the comment to be `GITHUB` not `TWITTER`

2023-05-07 18:58 UTC, Yarob50 commented on readme.md
> +                    <!-- TWITTER -->
@dr-almukhtar 
طبعا عشان تكون الصورة واضحة كل اللي محتاجه الآن انك تسوي التعديل اللي طلبته في التعليق فوق و ترجع تسوي push مانك محتاج تسوي PR كمان مرة.. ال push يكفي

2023-05-07 19:17 UTC, dr-almukhtar commented on readme.md
> +                    <!-- TWITTER -->
تمام استاذ صححت وعملت push

2023-05-08 12:20 UTC, Yarob50 approved these changes

2023-05-08 12:20 UTC, merged